name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - task: biome
            name: "Run Biome CI"
            command: "bun biome ci ."
          - task: vitest
            name: "Run test runner"
            command: "bun run test"
          - task: build
            name: "Run Vite build"
            command: "bun run build"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup tools
        uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2.2.3
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Fetch docs assets
        run: bun run fetch-docs-ja-jp
      - name: ${{ matrix.name }}
        run: ${{ matrix.command }}
